<script setup lang="ts">
import {ref,reactive,computed} from 'vue'
import {ElMessage} from 'element-plus'
import {yuan,requestKey} from '../commerce'
import PageShell from '../PageShell.vue'
import Icon from '../Icon.vue'
import {usePage} from '../page'
import {api,bytes,quotaText,limitText,type User,type Plan} from '../api'
const users=ref<User[]>([]),plans=ref<Plan[]>([]),userPage=ref(1),search=ref(''),dialog=ref(false),editID=ref(0)
const form=reactive({username:'',password:'',enabled:true,plan_id:0})
const rechargeDialog=ref(false),rechargeUser=ref<User|null>(null),recharge=reactive({amount:'100.00',note:'',request_key:''})
function credit(u:User){rechargeUser.value=u;Object.assign(recharge,{amount:'100.00',note:'',request_key:requestKey()});rechargeDialog.value=true}
async function saveCredit(){if(!rechargeUser.value)return;await run(async()=>{await api(`admin/users/${rechargeUser.value!.id}/recharge`,'POST',recharge);rechargeDialog.value=false;await refresh();ElMessage.success('充值成功，已记入余额明细')})}
const filtered=computed(()=>users.value.filter(u=>u.username.toLowerCase().includes(search.value.toLowerCase())))
const paged=computed(()=>filtered.value.slice((userPage.value-1)*25,userPage.value*25))
const {me,loading,error,busy,run,refresh}=usePage(async()=>{const[u,p]=await Promise.all([api<User[]>('admin/users'),api<Plan[]>('admin/plans')]);users.value=u;plans.value=p},{admin:true,interval:5000})
function edit(u?:User){editID.value=u?.id||0;Object.assign(form,{username:u?.username||'',password:'',enabled:u?.enabled??true,plan_id:u?.plan_id||0});dialog.value=true}
async function save(){await run(async()=>{await api(`admin/users${editID.value?'/'+editID.value:''}`,editID.value?'PUT':'POST',form);dialog.value=false;await refresh();ElMessage.success('用户已保存')})}
</script>
<template><PageShell :me="me" :loading="loading" :error="error" active="users" admin><section class="surface"><div class="section-header"><strong>用户管理</strong><el-button @click="edit()"><Icon name="add" />创建用户</el-button></div><div class="section-body"><el-input v-model="search" placeholder="搜索用户名" clearable class="user-search" @input="userPage=1" /><el-table :data="paged"><el-table-column prop="username" label="用户" min-width="150" /><el-table-column label="状态" width="90"><template #default="{row}">{{!row.enabled?'已禁用':row.expires_at&&new Date(row.expires_at).getTime()<=Date.now()?'已到期':'已启用'}}</template></el-table-column><el-table-column label="余额 / 元" width="120"><template #default="{row}">{{yuan(row.balance_cents||0)}}</template></el-table-column><el-table-column prop="plan_name" label="套餐" min-width="160" /><el-table-column label="每节点限速" width="140"><template #default="{row}">{{row.plan_id?limitText(row.speed_mbps,'Mbps'):'—'}}</template></el-table-column><el-table-column label="流量 / 额度" min-width="200"><template #default="{row}">{{bytes(row.traffic_bytes)}} / {{row.plan_id?quotaText(row.quota_bytes):'未分配套餐'}}</template></el-table-column><el-table-column label="规则上限" width="100"><template #default="{row}">{{row.plan_id?limitText(row.max_rules):'—'}}</template></el-table-column><el-table-column label="操作" width="240"><template #default="{row}"><div class="user-row-actions"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="primary" @click="credit(row)">充值</el-button><a class="text-link" :href="`/admin/users/${row.id}/forward_rules`">管理规则 ({{row.rule_count}})</a></div></template></el-table-column></el-table><el-pagination v-model:current-page="userPage" :page-size="25" :total="filtered.length" layout="prev, pager, next, total" class="user-pagination" /></div></section>
 <el-dialog v-model="dialog" :title="editID?'编辑用户':'创建用户'" width="520px"><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="form.username" /></el-form-item><el-form-item :label="editID?'新密码（留空不修改）':'密码（至少 12 字节）'"><el-input v-model="form.password" type="password" show-password /></el-form-item><el-form-item label="套餐"><el-select v-model="form.plan_id" filterable><el-option label="未分配套餐" :value="0" /><el-option v-for="p in plans" :key="p.id" :label="p.name+(p.enabled?'':'（停用）')" :value="p.id" /></el-select><span class="field-tip">限速、流量、有效期和节点组权限均由套餐决定。更换套餐不会清空已用流量。</span></el-form-item><el-form-item label="启用账号"><el-switch v-model="form.enabled" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存用户</el-button></template></el-dialog>
<el-dialog v-model="rechargeDialog" title="管理员充值余额" width="500px"><p>{{rechargeUser?.username}} · 当前余额 {{yuan(rechargeUser?.balance_cents||0)}} 元</p><el-form label-position="top"><el-form-item label="充值金额 / 元"><el-input v-model="recharge.amount" inputmode="decimal" /></el-form-item><el-form-item label="充值备注"><el-input v-model="recharge.note" type="textarea" :rows="2" maxlength="300" placeholder="填写充值原因或线下收款说明" /></el-form-item></el-form><p class="field-tip">确认后立即增加余额，并记录操作管理员、金额和备注。</p><template #footer><el-button @click="rechargeDialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="saveCredit">确认充值</el-button></template></el-dialog></PageShell></template>
