<script setup lang="ts">
import {ElMessage} from 'element-plus'
import {ref} from 'vue'
import PageShell from '../PageShell.vue'
import {usePage} from '../page'
import {api} from '../api'
import {yuan,cycleName,dateText,openCheckout,type Checkout} from '../commerce'
type Order={payment_method_name:string;can_pay:boolean;id:number;order_no:string;kind:string;plan_name:string;cycle:string;amount_cents:number;status:string;created_at:string;paid_at:string|null;snapshot:{expires_at?:string|null;next_reset_at?:string|null;note?:string}}
const orders=ref<Order[]>([]),total=ref(0),page=ref(1),detail=ref<Order|null>(null),dialog=ref(false)
const {me,loading,error,refresh}=usePage(async()=>{const data=await api<{items:Order[];total:number}>(`orders?page=${page.value}`);orders.value=data.items;total.value=data.total},{interval:15000})
function show(o:Order){detail.value=o;dialog.value=true}
function kind(o:Order){return o.kind==='recharge'?'余额充值':o.kind==='renewal'?'套餐续费':'套餐购买'}
const returned=new URLSearchParams(location.search).has('payment'),paying=ref(0)
async function pay(order:Order){if(paying.value)return;paying.value=order.id;try{const result=await api<{checkout:Checkout;status:string}>(`orders/${order.id}/pay`,'POST',{});if(result.status==='paid'){await refresh();ElMessage.success('充值订单已完成')}else openCheckout(result.checkout)}catch(e){ElMessage.error((e as Error).message)}finally{paying.value=0}}
</script>
<template><PageShell :me="me" :loading="loading" :error="error" active="orders"><p v-if="returned" class="field-tip">已从支付页面返回，到账以付款通知为准；尚未完成的订单会自动刷新。</p><section class="surface"><div class="section-header"><strong>我的订单</strong><a class="text-link" href="/shop">前往商城</a></div><div class="section-body"><el-table :data="orders" empty-text="暂无订单"><el-table-column label="订单号" min-width="235"><template #default="{row}"><el-button link type="primary" @click="show(row)">{{row.order_no}}</el-button></template></el-table-column><el-table-column label="类型" width="100"><template #default="{row}">{{kind(row)}}</template></el-table-column><el-table-column label="内容" min-width="175"><template #default="{row}">{{row.kind==='recharge'?(row.payment_method_name||'管理员充值'):row.plan_name+' · '+cycleName(row.cycle)}}</template></el-table-column><el-table-column label="金额 / 元" width="110"><template #default="{row}">{{yuan(row.amount_cents)}}</template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="row.status==='paid'?'success':'info'">{{row.status==='paid'?'已完成':row.status==='pending'?'待支付':'已取消'}}</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button v-if="row.can_pay" link type="primary" :loading="paying===row.id" @click="pay(row)">继续支付</el-button></template></el-table-column><el-table-column label="创建时间" min-width="180"><template #default="{row}">{{dateText(row.created_at)}}</template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev, pager, next, total" class="user-pagination" @current-change="refresh"/></div></section><el-dialog v-model="dialog" title="订单详情" width="540px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="订单号">{{detail.order_no}}</el-descriptions-item><el-descriptions-item label="类型">{{kind(detail)}}</el-descriptions-item><el-descriptions-item label="金额">{{yuan(detail.amount_cents)}} 元</el-descriptions-item><el-descriptions-item label="完成时间">{{dateText(detail.paid_at,'尚未完成')}}</el-descriptions-item><template v-if="detail.kind!=='recharge'"><el-descriptions-item label="套餐">{{detail.plan_name}} · {{cycleName(detail.cycle)}}</el-descriptions-item><el-descriptions-item label="购买时预计到期">{{dateText(detail.snapshot.expires_at)}}</el-descriptions-item><el-descriptions-item label="购买时下次重置">{{dateText(detail.snapshot.next_reset_at,'无自动重置')}}</el-descriptions-item></template><el-descriptions-item v-else label="充值备注">{{detail.snapshot.note}}</el-descriptions-item></el-descriptions></el-dialog></PageShell></template>
