CREATE TABLE site_settings (id integer PRIMARY KEY CHECK(id=1), announcement text NOT NULL DEFAULT '', updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO site_settings(id,announcement) VALUES(1,'欢迎使用 Nekopass。');
CREATE TABLE rule_groups (id bigserial PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 64), UNIQUE(user_id,name));
ALTER TABLE nodes ADD COLUMN public_address text NOT NULL DEFAULT '';
ALTER TABLE rules ADD COLUMN name text NOT NULL DEFAULT '';
ALTER TABLE rules ADD COLUMN group_id bigint REFERENCES rule_groups(id) ON DELETE SET NULL;
ALTER TABLE rules ADD COLUMN targets jsonb NOT NULL DEFAULT '[]';
ALTER TABLE rules ADD COLUMN balance text NOT NULL DEFAULT 'random' CHECK(balance IN ('random','round_robin','least_connections'));
ALTER TABLE rules ADD COLUMN speed_mbps bigint NOT NULL DEFAULT 0 CHECK(speed_mbps BETWEEN 0 AND 100000);
ALTER TABLE rules ADD COLUMN ip_limit integer NOT NULL DEFAULT 0 CHECK(ip_limit BETWEEN 0 AND 1000000);
ALTER TABLE rules ADD COLUMN connection_limit integer NOT NULL DEFAULT 0 CHECK(connection_limit BETWEEN 0 AND 1000000);
ALTER TABLE rules ADD COLUMN proxy_accept text NOT NULL DEFAULT 'off' CHECK(proxy_accept IN ('off','v1','v2'));
ALTER TABLE rules ADD COLUMN proxy_send text NOT NULL DEFAULT 'off' CHECK(proxy_send IN ('off','v1','v2'));
ALTER TABLE rules ADD COLUMN proxy_trusted_cidrs jsonb NOT NULL DEFAULT '[]';
ALTER TABLE rules ADD COLUMN traffic_baseline bigint NOT NULL DEFAULT 0;
ALTER TABLE rules ADD COLUMN config_revision bigint NOT NULL DEFAULT 0;
UPDATE rules SET name=target_host||':'||target_port, targets=jsonb_build_array(CASE WHEN strpos(target_host,':')>0 THEN '['||target_host||']' ELSE target_host END||':'||target_port);
CREATE TABLE rule_events (id bigserial PRIMARY KEY,node_id bigint NOT NULL,rule_id bigint NOT NULL,user_id bigint NOT NULL,traffic_bytes bigint NOT NULL CHECK(traffic_bytes>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX rule_events_rule_time ON rule_events(rule_id,created_at);
CREATE INDEX rule_events_user_time ON rule_events(user_id,created_at);
INSERT INTO schema_version VALUES(2);
