// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrentGrant struct {
	NodeID         int64 `json:"node_id"`
	UserID         int64 `json:"user_id"`
	Issued         int64 `json:"issued"`
	Spent          int64 `json:"spent"`
	Released       int64 `json:"released"`
	Traffic        int64 `json:"traffic"`
	UnlimitedSpent int64 `json:"unlimited_spent"`
	UnlimitedOpen  bool  `json:"unlimited_open"`
	QuotaEpoch     int64 `json:"quota_epoch"`
}

type Grant struct {
	NodeID         int64 `json:"node_id"`
	UserID         int64 `json:"user_id"`
	Issued         int64 `json:"issued"`
	Spent          int64 `json:"spent"`
	Released       int64 `json:"released"`
	Traffic        int64 `json:"traffic"`
	UnlimitedSpent int64 `json:"unlimited_spent"`
	UnlimitedOpen  bool  `json:"unlimited_open"`
	QuotaEpoch     int64 `json:"quota_epoch"`
}

type Node struct {
	ID                   int64              `json:"id"`
	Name                 string             `json:"name"`
	TokenHash            string             `json:"token_hash"`
	InstanceID           string             `json:"instance_id"`
	LastSeen             pgtype.Timestamptz `json:"last_seen"`
	AppliedRevision      int64              `json:"applied_revision"`
	SyncError            string             `json:"sync_error"`
	ActiveConnections    int64              `json:"active_connections"`
	PublicAddress        string             `json:"public_address"`
	Enabled              bool               `json:"enabled"`
	Notes                string             `json:"notes"`
	ListenHost           string             `json:"listen_host"`
	PortMin              int32              `json:"port_min"`
	PortMax              int32              `json:"port_max"`
	MaxConnections       int64              `json:"max_connections"`
	DialTimeoutSeconds   int32              `json:"dial_timeout_seconds"`
	IdleTimeoutSeconds   int32              `json:"idle_timeout_seconds"`
	ProbeIntervalSeconds int32              `json:"probe_interval_seconds"`
	DiskPath             string             `json:"disk_path"`
	NetworkInterfaces    []byte             `json:"network_interfaces"`
	Probe                []byte             `json:"probe"`
	ProbeReceivedAt      pgtype.Timestamptz `json:"probe_received_at"`
	ConfigRevision       int64              `json:"config_revision"`
	Token                string             `json:"token"`
	AllowDirect          bool               `json:"allow_direct"`
	TunnelExitEnabled    bool               `json:"tunnel_exit_enabled"`
	TunnelProtocol       string             `json:"tunnel_protocol"`
	TunnelListenHost     string             `json:"tunnel_listen_host"`
	TunnelListenPort     int32              `json:"tunnel_listen_port"`
	TunnelPublicHost     string             `json:"tunnel_public_host"`
	IngressEnabled       bool               `json:"ingress_enabled"`
	TlsConfig            []byte             `json:"tls_config"`
	TlsCertificate       string             `json:"tls_certificate"`
	TlsPrivateKey        string             `json:"tls_private_key"`
	TlsCa                string             `json:"tls_ca"`
	TlsStatus            string             `json:"tls_status"`
	TlsError             string             `json:"tls_error"`
	TlsNotAfter          pgtype.Timestamptz `json:"tls_not_after"`
	TlsGeneration        int64              `json:"tls_generation"`
	ProtocolVersion      int32              `json:"protocol_version"`
	AcmeAck              int64              `json:"acme_ack"`
	AgentVersion         string             `json:"agent_version"`
	UpdateSupported      bool               `json:"update_supported"`
}

type NodeAcmeAccount struct {
	NodeID       int64  `json:"node_id"`
	DirectoryUrl string `json:"directory_url"`
	Email        string `json:"email"`
	PrivateKey   string `json:"private_key"`
	Registration []byte `json:"registration"`
}

type NodeAcmeChallenge struct {
	NodeID           int64              `json:"node_id"`
	Domain           string             `json:"domain"`
	Token            string             `json:"token"`
	KeyAuthorization string             `json:"key_authorization"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Revision         int64              `json:"revision"`
}

type NodeDdn struct {
	NodeID           int64              `json:"node_id"`
	Config           []byte             `json:"config"`
	Generation       int64              `json:"generation"`
	Status           []byte             `json:"status"`
	StatusReceivedAt pgtype.Timestamptz `json:"status_received_at"`
}

type NodeGroup struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
	SortOrder   int32  `json:"sort_order"`
	Strategy    string `json:"strategy"`
}

type NodeGroupMember struct {
	GroupID  int64 `json:"group_id"`
	NodeID   int64 `json:"node_id"`
	Weight   int32 `json:"weight"`
	Priority int32 `json:"priority"`
}

type NodeInstallTicket struct {
	TokenHash string             `json:"token_hash"`
	NodeID    int64              `json:"node_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	Config    []byte             `json:"config"`
}

type NodeTunnelLink struct {
	IngressNodeID int64  `json:"ingress_node_id"`
	EgressNodeID  int64  `json:"egress_node_id"`
	Token         string `json:"token"`
}

type NodeUpdate struct {
	NodeID      int64              `json:"node_id"`
	Generation  int64              `json:"generation"`
	Version     string             `json:"version"`
	State       string             `json:"state"`
	Error       string             `json:"error"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OldEntitlement struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	PasswordHash        string             `json:"password_hash"`
	IsAdmin             bool               `json:"is_admin"`
	Enabled             bool               `json:"enabled"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	SpeedBps            int64              `json:"speed_bps"`
	QuotaBytes          int64              `json:"quota_bytes"`
	MaxRules            int32              `json:"max_rules"`
	MaxConnections      int64              `json:"max_connections"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	PlanID              pgtype.Int8        `json:"plan_id"`
	PlanStartedAt       pgtype.Timestamptz `json:"plan_started_at"`
	DurationDays        interface{}        `json:"duration_days"`
	NodeIds             interface{}        `json:"node_ids"`
	Signature           []byte             `json:"signature"`
	RuleSpeedBps        pgtype.Int8        `json:"rule_speed_bps"`
	RuleIpLimit         pgtype.Int4        `json:"rule_ip_limit"`
	RuleConnectionLimit pgtype.Int4        `json:"rule_connection_limit"`
}

type Plan struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	Enabled             bool               `json:"enabled"`
	SpeedBps            int64              `json:"speed_bps"`
	QuotaBytes          int64              `json:"quota_bytes"`
	MaxRules            int32              `json:"max_rules"`
	MaxConnections      int64              `json:"max_connections"`
	IpLimit             int32              `json:"ip_limit"`
	RuleSpeedBps        int64              `json:"rule_speed_bps"`
	RuleIpLimit         int32              `json:"rule_ip_limit"`
	RuleConnectionLimit int32              `json:"rule_connection_limit"`
	DurationDays        int32              `json:"duration_days"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Prices              []byte             `json:"prices"`
	PurchaseLimit       int32              `json:"purchase_limit"`
}

type PlanNodeGroup struct {
	PlanID  int64 `json:"plan_id"`
	GroupID int64 `json:"group_id"`
}

type Revision struct {
	ID    int32 `json:"id"`
	Value int64 `json:"value"`
}

type Rule struct {
	ID                int64       `json:"id"`
	UserID            int64       `json:"user_id"`
	NodeID            int64       `json:"node_id"`
	ListenHost        string      `json:"listen_host"`
	ListenPort        int32       `json:"listen_port"`
	TargetHost        string      `json:"target_host"`
	TargetPort        int32       `json:"target_port"`
	Enabled           bool        `json:"enabled"`
	Name              string      `json:"name"`
	GroupID           pgtype.Int8 `json:"group_id"`
	Targets           []byte      `json:"targets"`
	Balance           string      `json:"balance"`
	SpeedMbps         int64       `json:"speed_mbps"`
	IpLimit           int32       `json:"ip_limit"`
	ConnectionLimit   int32       `json:"connection_limit"`
	ProxyAccept       string      `json:"proxy_accept"`
	ProxySend         string      `json:"proxy_send"`
	ProxyTrustedCidrs []byte      `json:"proxy_trusted_cidrs"`
	TrafficBaseline   int64       `json:"traffic_baseline"`
	ConfigRevision    int64       `json:"config_revision"`
	EgressNodeID      pgtype.Int8 `json:"egress_node_id"`
}

type RuleEvent struct {
	ID           int64              `json:"id"`
	NodeID       int64              `json:"node_id"`
	RuleID       int64              `json:"rule_id"`
	UserID       int64              `json:"user_id"`
	TrafficBytes int64              `json:"traffic_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RuleGroup struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type RuleUsage struct {
	NodeID  int64 `json:"node_id"`
	RuleID  int64 `json:"rule_id"`
	UserID  int64 `json:"user_id"`
	Traffic int64 `json:"traffic"`
}

type SchemaVersion struct {
	Version int32 `json:"version"`
}

type Session struct {
	TokenHash       string             `json:"token_hash"`
	UserID          int64              `json:"user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CookieRenewedAt pgtype.Timestamptz `json:"cookie_renewed_at"`
}

type ShopOrder struct {
	ID          int64              `json:"id"`
	OrderNo     string             `json:"order_no"`
	UserID      int64              `json:"user_id"`
	Kind        string             `json:"kind"`
	PlanID      pgtype.Int8        `json:"plan_id"`
	PlanName    string             `json:"plan_name"`
	Cycle       string             `json:"cycle"`
	AmountCents int64              `json:"amount_cents"`
	Status      string             `json:"status"`
	RequestKey  string             `json:"request_key"`
	ActorID     pgtype.Int8        `json:"actor_id"`
	Snapshot    []byte             `json:"snapshot"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

type SiteSetting struct {
	ID           int32              `json:"id"`
	Announcement string             `json:"announcement"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Config       []byte             `json:"config"`
	ApiKeyHash   string             `json:"api_key_hash"`
	ApiKeyUserID pgtype.Int8        `json:"api_key_user_id"`
}

type UsageEvent struct {
	ID           int64              `json:"id"`
	NodeID       int64              `json:"node_id"`
	UserID       int64              `json:"user_id"`
	TrafficBytes int64              `json:"traffic_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    int64              `json:"id"`
	Username              string             `json:"username"`
	PasswordHash          string             `json:"password_hash"`
	IsAdmin               bool               `json:"is_admin"`
	Enabled               bool               `json:"enabled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	PlanID                pgtype.Int8        `json:"plan_id"`
	PlanStartedAt         pgtype.Timestamptz `json:"plan_started_at"`
	SubscriptionManaged   bool               `json:"subscription_managed"`
	SubscriptionExpiresAt pgtype.Timestamptz `json:"subscription_expires_at"`
	NextResetAt           pgtype.Timestamptz `json:"next_reset_at"`
	ResetAnchorAt         pgtype.Timestamptz `json:"reset_anchor_at"`
	ResetIndex            int32              `json:"reset_index"`
	QuotaEpoch            int64              `json:"quota_epoch"`
	SpeedBps              int64              `json:"speed_bps"`
	QuotaBytes            int64              `json:"quota_bytes"`
	MaxRules              int32              `json:"max_rules"`
	MaxConnections        int64              `json:"max_connections"`
	IpLimit               int32              `json:"ip_limit"`
	RuleSpeedBps          int64              `json:"rule_speed_bps"`
	RuleIpLimit           int32              `json:"rule_ip_limit"`
	RuleConnectionLimit   int32              `json:"rule_connection_limit"`
	ResourceExpiresAt     pgtype.Timestamptz `json:"resource_expires_at"`
	TrafficBaseBytes      int64              `json:"traffic_base_bytes"`
	ResourcesRevision     int64              `json:"resources_revision"`
}

type UserEntitlement struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	IsAdmin             bool               `json:"is_admin"`
	AccountEnabled      bool               `json:"account_enabled"`
	PlanID              pgtype.Int8        `json:"plan_id"`
	PlanStartedAt       pgtype.Timestamptz `json:"plan_started_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Enabled             pgtype.Bool        `json:"enabled"`
	PlanEnabled         bool               `json:"plan_enabled"`
	PlanName            string             `json:"plan_name"`
	ExpiresAt           interface{}        `json:"expires_at"`
	SpeedBps            int64              `json:"speed_bps"`
	QuotaBytes          int64              `json:"quota_bytes"`
	MaxRules            int32              `json:"max_rules"`
	MaxConnections      int64              `json:"max_connections"`
	IpLimit             int32              `json:"ip_limit"`
	RuleSpeedBps        int64              `json:"rule_speed_bps"`
	RuleIpLimit         int32              `json:"rule_ip_limit"`
	RuleConnectionLimit int32              `json:"rule_connection_limit"`
	QuotaEpoch          int64              `json:"quota_epoch"`
	NextResetAt         pgtype.Timestamptz `json:"next_reset_at"`
	SubscriptionManaged bool               `json:"subscription_managed"`
	TrafficBaseBytes    int64              `json:"traffic_base_bytes"`
	ResourcesRevision   int64              `json:"resources_revision"`
}

type UserNode struct {
	UserID int64 `json:"user_id"`
	NodeID int64 `json:"node_id"`
}

type UserNodeGroup struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

type UserResourceChange struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	ActorID     pgtype.Int8        `json:"actor_id"`
	BeforeState []byte             `json:"before_state"`
	AfterState  []byte             `json:"after_state"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WalletAccount struct {
	UserID       int64              `json:"user_id"`
	BalanceCents int64              `json:"balance_cents"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WalletEntry struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	OrderID           pgtype.Int8        `json:"order_id"`
	AmountCents       int64              `json:"amount_cents"`
	BalanceAfterCents int64              `json:"balance_after_cents"`
	Kind              string             `json:"kind"`
	ActorID           pgtype.Int8        `json:"actor_id"`
	Note              string             `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
