// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
)

const bumpRevision = `-- name: BumpRevision :exec
UPDATE revision SET value=value+1 WHERE id=1
`

func (q *Queries) BumpRevision(ctx context.Context) error {
	_, err := q.db.Exec(ctx, bumpRevision)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const findNodeByToken = `-- name: FindNodeByToken :one
SELECT id, name, token_hash, instance_id, last_seen, applied_revision, sync_error, active_connections, public_address, enabled, notes, listen_host, port_min, port_max, max_connections, dial_timeout_seconds, idle_timeout_seconds, probe_interval_seconds, disk_path, network_interfaces, probe, probe_received_at, config_revision, token, allow_direct, tunnel_exit_enabled, tunnel_protocol, tunnel_listen_host, tunnel_listen_port, tunnel_public_host, ingress_enabled, tls_config, tls_certificate, tls_private_key, tls_ca, tls_status, tls_error, tls_not_after, tls_generation, protocol_version, acme_ack, agent_version, update_supported FROM nodes WHERE token_hash=$1
`

func (q *Queries) FindNodeByToken(ctx context.Context, tokenHash string) (Node, error) {
	row := q.db.QueryRow(ctx, findNodeByToken, tokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.InstanceID,
		&i.LastSeen,
		&i.AppliedRevision,
		&i.SyncError,
		&i.ActiveConnections,
		&i.PublicAddress,
		&i.Enabled,
		&i.Notes,
		&i.ListenHost,
		&i.PortMin,
		&i.PortMax,
		&i.MaxConnections,
		&i.DialTimeoutSeconds,
		&i.IdleTimeoutSeconds,
		&i.ProbeIntervalSeconds,
		&i.DiskPath,
		&i.NetworkInterfaces,
		&i.Probe,
		&i.ProbeReceivedAt,
		&i.ConfigRevision,
		&i.Token,
		&i.AllowDirect,
		&i.TunnelExitEnabled,
		&i.TunnelProtocol,
		&i.TunnelListenHost,
		&i.TunnelListenPort,
		&i.TunnelPublicHost,
		&i.IngressEnabled,
		&i.TlsConfig,
		&i.TlsCertificate,
		&i.TlsPrivateKey,
		&i.TlsCa,
		&i.TlsStatus,
		&i.TlsError,
		&i.TlsNotAfter,
		&i.TlsGeneration,
		&i.ProtocolVersion,
		&i.AcmeAck,
		&i.AgentVersion,
		&i.UpdateSupported,
	)
	return i, err
}

const findSession = `-- name: FindSession :one
SELECT u.id, u.username, u.password_hash, u.is_admin, u.enabled, u.created_at, u.plan_id, u.plan_started_at, u.subscription_managed, u.subscription_expires_at, u.next_reset_at, u.reset_anchor_at, u.reset_index, u.quota_epoch, u.speed_bps, u.quota_bytes, u.max_rules, u.max_connections, u.ip_limit, u.rule_speed_bps, u.rule_ip_limit, u.rule_connection_limit, u.resource_expires_at, u.traffic_base_bytes, u.resources_revision FROM users u JOIN sessions s ON s.user_id=u.id
WHERE s.token_hash=$1 AND s.expires_at>now()
`

func (q *Queries) FindSession(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, findSession, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Enabled,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanStartedAt,
		&i.SubscriptionManaged,
		&i.SubscriptionExpiresAt,
		&i.NextResetAt,
		&i.ResetAnchorAt,
		&i.ResetIndex,
		&i.QuotaEpoch,
		&i.SpeedBps,
		&i.QuotaBytes,
		&i.MaxRules,
		&i.MaxConnections,
		&i.IpLimit,
		&i.RuleSpeedBps,
		&i.RuleIpLimit,
		&i.RuleConnectionLimit,
		&i.ResourceExpiresAt,
		&i.TrafficBaseBytes,
		&i.ResourcesRevision,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT id, username, password_hash, is_admin, enabled, created_at, plan_id, plan_started_at, subscription_managed, subscription_expires_at, next_reset_at, reset_anchor_at, reset_index, quota_epoch, speed_bps, quota_bytes, max_rules, max_connections, ip_limit, rule_speed_bps, rule_ip_limit, rule_connection_limit, resource_expires_at, traffic_base_bytes, resources_revision FROM users WHERE id = $1
`

func (q *Queries) FindUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Enabled,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanStartedAt,
		&i.SubscriptionManaged,
		&i.SubscriptionExpiresAt,
		&i.NextResetAt,
		&i.ResetAnchorAt,
		&i.ResetIndex,
		&i.QuotaEpoch,
		&i.SpeedBps,
		&i.QuotaBytes,
		&i.MaxRules,
		&i.MaxConnections,
		&i.IpLimit,
		&i.RuleSpeedBps,
		&i.RuleIpLimit,
		&i.RuleConnectionLimit,
		&i.ResourceExpiresAt,
		&i.TrafficBaseBytes,
		&i.ResourcesRevision,
	)
	return i, err
}

const findUserByName = `-- name: FindUserByName :one
SELECT id, username, password_hash, is_admin, enabled, created_at, plan_id, plan_started_at, subscription_managed, subscription_expires_at, next_reset_at, reset_anchor_at, reset_index, quota_epoch, speed_bps, quota_bytes, max_rules, max_connections, ip_limit, rule_speed_bps, rule_ip_limit, rule_connection_limit, resource_expires_at, traffic_base_bytes, resources_revision FROM users WHERE username = $1
`

func (q *Queries) FindUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Enabled,
		&i.CreatedAt,
		&i.PlanID,
		&i.PlanStartedAt,
		&i.SubscriptionManaged,
		&i.SubscriptionExpiresAt,
		&i.NextResetAt,
		&i.ResetAnchorAt,
		&i.ResetIndex,
		&i.QuotaEpoch,
		&i.SpeedBps,
		&i.QuotaBytes,
		&i.MaxRules,
		&i.MaxConnections,
		&i.IpLimit,
		&i.RuleSpeedBps,
		&i.RuleIpLimit,
		&i.RuleConnectionLimit,
		&i.ResourceExpiresAt,
		&i.TrafficBaseBytes,
		&i.ResourcesRevision,
	)
	return i, err
}
