// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: api/control.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Usage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Spent          int64                  `protobuf:"varint,2,opt,name=spent,proto3" json:"spent,omitempty"`
	Released       int64                  `protobuf:"varint,3,opt,name=released,proto3" json:"released,omitempty"`
	Traffic        int64                  `protobuf:"varint,4,opt,name=traffic,proto3" json:"traffic,omitempty"`
	UnlimitedSpent int64                  `protobuf:"varint,5,opt,name=unlimited_spent,json=unlimitedSpent,proto3" json:"unlimited_spent,omitempty"`
	QuotaUnlimited bool                   `protobuf:"varint,6,opt,name=quota_unlimited,json=quotaUnlimited,proto3" json:"quota_unlimited,omitempty"`
	QuotaEpoch     int64                  `protobuf:"varint,7,opt,name=quota_epoch,json=quotaEpoch,proto3" json:"quota_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

func (x *Usage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Usage) GetSpent() int64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *Usage) GetReleased() int64 {
	if x != nil {
		return x.Released
	}
	return 0
}

func (x *Usage) GetTraffic() int64 {
	if x != nil {
		return x.Traffic
	}
	return 0
}

func (x *Usage) GetUnlimitedSpent() int64 {
	if x != nil {
		return x.UnlimitedSpent
	}
	return 0
}

func (x *Usage) GetQuotaUnlimited() bool {
	if x != nil {
		return x.QuotaUnlimited
	}
	return false
}

func (x *Usage) GetQuotaEpoch() int64 {
	if x != nil {
		return x.QuotaEpoch
	}
	return 0
}

type RuleUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Traffic       int64                  `protobuf:"varint,2,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUsage) Reset() {
	*x = RuleUsage{}
	mi := &file_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUsage) ProtoMessage() {}

func (x *RuleUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUsage.ProtoReflect.Descriptor instead.
func (*RuleUsage) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *RuleUsage) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleUsage) GetTraffic() int64 {
	if x != nil {
		return x.Traffic
	}
	return 0
}

type AgentMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Usage             []*Usage               `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty"`
	RuleUsage         []*RuleUsage           `protobuf:"bytes,2,rep,name=rule_usage,json=ruleUsage,proto3" json:"rule_usage,omitempty"`
	RequestUsers      []int64                `protobuf:"varint,3,rep,packed,name=request_users,json=requestUsers,proto3" json:"request_users,omitempty"`
	AppliedRevision   int64                  `protobuf:"varint,4,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	InstanceId        string                 `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Probe             *Probe                 `protobuf:"bytes,8,opt,name=probe,proto3" json:"probe,omitempty"`
	ProtocolVersion   int32                  `protobuf:"varint,9,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AcmeAck           int64                  `protobuf:"varint,10,opt,name=acme_ack,json=acmeAck,proto3" json:"acme_ack,omitempty"`
	DdnsStatus        *DDNSStatus            `protobuf:"bytes,11,opt,name=ddns_status,json=ddnsStatus,proto3" json:"ddns_status,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,12,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UpdateStatus      *UpdateStatus          `protobuf:"bytes,13,opt,name=update_status,json=updateStatus,proto3" json:"update_status,omitempty"`
	UpdateSupported   bool                   `protobuf:"varint,14,opt,name=update_supported,json=updateSupported,proto3" json:"update_supported,omitempty"`
	RestoreState      bool                   `protobuf:"varint,15,opt,name=restore_state,json=restoreState,proto3" json:"restore_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetUsage() []*Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *AgentMessage) GetRuleUsage() []*RuleUsage {
	if x != nil {
		return x.RuleUsage
	}
	return nil
}

func (x *AgentMessage) GetRequestUsers() []int64 {
	if x != nil {
		return x.RequestUsers
	}
	return nil
}

func (x *AgentMessage) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *AgentMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentMessage) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *AgentMessage) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AgentMessage) GetProbe() *Probe {
	if x != nil {
		return x.Probe
	}
	return nil
}

func (x *AgentMessage) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AgentMessage) GetAcmeAck() int64 {
	if x != nil {
		return x.AcmeAck
	}
	return 0
}

func (x *AgentMessage) GetDdnsStatus() *DDNSStatus {
	if x != nil {
		return x.DdnsStatus
	}
	return nil
}

func (x *AgentMessage) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentMessage) GetUpdateStatus() *UpdateStatus {
	if x != nil {
		return x.UpdateStatus
	}
	return nil
}

func (x *AgentMessage) GetUpdateSupported() bool {
	if x != nil {
		return x.UpdateSupported
	}
	return false
}

func (x *AgentMessage) GetRestoreState() bool {
	if x != nil {
		return x.RestoreState
	}
	return false
}

type UserPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled        bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ExpiresUnix    int64                  `protobuf:"varint,3,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	SpeedBps       int64                  `protobuf:"varint,4,opt,name=speed_bps,json=speedBps,proto3" json:"speed_bps,omitempty"`
	Issued         int64                  `protobuf:"varint,5,opt,name=issued,proto3" json:"issued,omitempty"`
	MaxConnections int64                  `protobuf:"varint,6,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	IpLimit        int32                  `protobuf:"varint,7,opt,name=ip_limit,json=ipLimit,proto3" json:"ip_limit,omitempty"`
	QuotaUnlimited bool                   `protobuf:"varint,8,opt,name=quota_unlimited,json=quotaUnlimited,proto3" json:"quota_unlimited,omitempty"`
	QuotaEpoch     int64                  `protobuf:"varint,9,opt,name=quota_epoch,json=quotaEpoch,proto3" json:"quota_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserPolicy) Reset() {
	*x = UserPolicy{}
	mi := &file_api_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPolicy) ProtoMessage() {}

func (x *UserPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPolicy.ProtoReflect.Descriptor instead.
func (*UserPolicy) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3}
}

func (x *UserPolicy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserPolicy) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *UserPolicy) GetSpeedBps() int64 {
	if x != nil {
		return x.SpeedBps
	}
	return 0
}

func (x *UserPolicy) GetIssued() int64 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *UserPolicy) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *UserPolicy) GetIpLimit() int32 {
	if x != nil {
		return x.IpLimit
	}
	return 0
}

func (x *UserPolicy) GetQuotaUnlimited() bool {
	if x != nil {
		return x.QuotaUnlimited
	}
	return false
}

func (x *UserPolicy) GetQuotaEpoch() int64 {
	if x != nil {
		return x.QuotaEpoch
	}
	return 0
}

type Rule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListenHost        string                 `protobuf:"bytes,3,opt,name=listen_host,json=listenHost,proto3" json:"listen_host,omitempty"`
	ListenPort        int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	TargetHost        string                 `protobuf:"bytes,5,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort        int32                  `protobuf:"varint,6,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Enabled           bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets           []string               `protobuf:"bytes,8,rep,name=targets,proto3" json:"targets,omitempty"`
	Balance           string                 `protobuf:"bytes,9,opt,name=balance,proto3" json:"balance,omitempty"`
	SpeedBps          int64                  `protobuf:"varint,10,opt,name=speed_bps,json=speedBps,proto3" json:"speed_bps,omitempty"`
	IpLimit           int32                  `protobuf:"varint,11,opt,name=ip_limit,json=ipLimit,proto3" json:"ip_limit,omitempty"`
	ConnectionLimit   int32                  `protobuf:"varint,12,opt,name=connection_limit,json=connectionLimit,proto3" json:"connection_limit,omitempty"`
	ProxyAccept       string                 `protobuf:"bytes,13,opt,name=proxy_accept,json=proxyAccept,proto3" json:"proxy_accept,omitempty"`
	ProxySend         string                 `protobuf:"bytes,14,opt,name=proxy_send,json=proxySend,proto3" json:"proxy_send,omitempty"`
	ProxyTrustedCidrs []string               `protobuf:"bytes,15,rep,name=proxy_trusted_cidrs,json=proxyTrustedCidrs,proto3" json:"proxy_trusted_cidrs,omitempty"`
	EgressNodeId      int64                  `protobuf:"varint,16,opt,name=egress_node_id,json=egressNodeId,proto3" json:"egress_node_id,omitempty"`
	TunnelHost        string                 `protobuf:"bytes,17,opt,name=tunnel_host,json=tunnelHost,proto3" json:"tunnel_host,omitempty"`
	TunnelPort        int32                  `protobuf:"varint,18,opt,name=tunnel_port,json=tunnelPort,proto3" json:"tunnel_port,omitempty"`
	TunnelToken       string                 `protobuf:"bytes,19,opt,name=tunnel_token,json=tunnelToken,proto3" json:"tunnel_token,omitempty"`
	IngressNodeId     int64                  `protobuf:"varint,20,opt,name=ingress_node_id,json=ingressNodeId,proto3" json:"ingress_node_id,omitempty"`
	TunnelProtocol    string                 `protobuf:"bytes,21,opt,name=tunnel_protocol,json=tunnelProtocol,proto3" json:"tunnel_protocol,omitempty"`
	Tls               *TLSClientConfig       `protobuf:"bytes,22,opt,name=tls,proto3" json:"tls,omitempty"`
	QuotaEpoch        int64                  `protobuf:"varint,23,opt,name=quota_epoch,json=quotaEpoch,proto3" json:"quota_epoch,omitempty"`
	Protocol          string                 `protobuf:"bytes,24,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{4}
}

func (x *Rule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rule) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Rule) GetListenHost() string {
	if x != nil {
		return x.ListenHost
	}
	return ""
}

func (x *Rule) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *Rule) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *Rule) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Rule) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Rule) GetSpeedBps() int64 {
	if x != nil {
		return x.SpeedBps
	}
	return 0
}

func (x *Rule) GetIpLimit() int32 {
	if x != nil {
		return x.IpLimit
	}
	return 0
}

func (x *Rule) GetConnectionLimit() int32 {
	if x != nil {
		return x.ConnectionLimit
	}
	return 0
}

func (x *Rule) GetProxyAccept() string {
	if x != nil {
		return x.ProxyAccept
	}
	return ""
}

func (x *Rule) GetProxySend() string {
	if x != nil {
		return x.ProxySend
	}
	return ""
}

func (x *Rule) GetProxyTrustedCidrs() []string {
	if x != nil {
		return x.ProxyTrustedCidrs
	}
	return nil
}

func (x *Rule) GetEgressNodeId() int64 {
	if x != nil {
		return x.EgressNodeId
	}
	return 0
}

func (x *Rule) GetTunnelHost() string {
	if x != nil {
		return x.TunnelHost
	}
	return ""
}

func (x *Rule) GetTunnelPort() int32 {
	if x != nil {
		return x.TunnelPort
	}
	return 0
}

func (x *Rule) GetTunnelToken() string {
	if x != nil {
		return x.TunnelToken
	}
	return ""
}

func (x *Rule) GetIngressNodeId() int64 {
	if x != nil {
		return x.IngressNodeId
	}
	return 0
}

func (x *Rule) GetTunnelProtocol() string {
	if x != nil {
		return x.TunnelProtocol
	}
	return ""
}

func (x *Rule) GetTls() *TLSClientConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Rule) GetQuotaEpoch() int64 {
	if x != nil {
		return x.QuotaEpoch
	}
	return 0
}

func (x *Rule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type TunnelLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngressNodeId int64                  `protobuf:"varint,1,opt,name=ingress_node_id,json=ingressNodeId,proto3" json:"ingress_node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelLink) Reset() {
	*x = TunnelLink{}
	mi := &file_api_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelLink) ProtoMessage() {}

func (x *TunnelLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelLink.ProtoReflect.Descriptor instead.
func (*TunnelLink) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{5}
}

func (x *TunnelLink) GetIngressNodeId() int64 {
	if x != nil {
		return x.IngressNodeId
	}
	return 0
}

func (x *TunnelLink) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EgressRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	IngressNodeId int64                  `protobuf:"varint,2,opt,name=ingress_node_id,json=ingressNodeId,proto3" json:"ingress_node_id,omitempty"`
	Targets       []string               `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuotaEpoch    int64                  `protobuf:"varint,5,opt,name=quota_epoch,json=quotaEpoch,proto3" json:"quota_epoch,omitempty"`
	ExpiresUnix   int64                  `protobuf:"varint,6,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressRule) Reset() {
	*x = EgressRule{}
	mi := &file_api_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressRule) ProtoMessage() {}

func (x *EgressRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressRule.ProtoReflect.Descriptor instead.
func (*EgressRule) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{6}
}

func (x *EgressRule) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *EgressRule) GetIngressNodeId() int64 {
	if x != nil {
		return x.IngressNodeId
	}
	return 0
}

func (x *EgressRule) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *EgressRule) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EgressRule) GetQuotaEpoch() int64 {
	if x != nil {
		return x.QuotaEpoch
	}
	return 0
}

func (x *EgressRule) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

func (x *EgressRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ControlMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Revision          int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Users             []*UserPolicy          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Rules             []*Rule                `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Node              *NodeConfig            `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	AcknowledgedUsage []*Usage               `protobuf:"bytes,5,rep,name=acknowledged_usage,json=acknowledgedUsage,proto3" json:"acknowledged_usage,omitempty"`
	TunnelLinks       []*TunnelLink          `protobuf:"bytes,6,rep,name=tunnel_links,json=tunnelLinks,proto3" json:"tunnel_links,omitempty"`
	EgressRules       []*EgressRule          `protobuf:"bytes,7,rep,name=egress_rules,json=egressRules,proto3" json:"egress_rules,omitempty"`
	Update            *UpdateRequest         `protobuf:"bytes,8,opt,name=update,proto3" json:"update,omitempty"`
	ControlEndpoint   string                 `protobuf:"bytes,9,opt,name=control_endpoint,json=controlEndpoint,proto3" json:"control_endpoint,omitempty"`
	StateRestore      *StateRestore          `protobuf:"bytes,10,opt,name=state_restore,json=stateRestore,proto3" json:"state_restore,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{7}
}

func (x *ControlMessage) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ControlMessage) GetUsers() []*UserPolicy {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ControlMessage) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ControlMessage) GetNode() *NodeConfig {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ControlMessage) GetAcknowledgedUsage() []*Usage {
	if x != nil {
		return x.AcknowledgedUsage
	}
	return nil
}

func (x *ControlMessage) GetTunnelLinks() []*TunnelLink {
	if x != nil {
		return x.TunnelLinks
	}
	return nil
}

func (x *ControlMessage) GetEgressRules() []*EgressRule {
	if x != nil {
		return x.EgressRules
	}
	return nil
}

func (x *ControlMessage) GetUpdate() *UpdateRequest {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ControlMessage) GetControlEndpoint() string {
	if x != nil {
		return x.ControlEndpoint
	}
	return ""
}

func (x *ControlMessage) GetStateRestore() *StateRestore {
	if x != nil {
		return x.StateRestore
	}
	return nil
}

type UserStateBaseline struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuotaEpoch     int64                  `protobuf:"varint,2,opt,name=quota_epoch,json=quotaEpoch,proto3" json:"quota_epoch,omitempty"`
	Issued         int64                  `protobuf:"varint,3,opt,name=issued,proto3" json:"issued,omitempty"`
	Spent          int64                  `protobuf:"varint,4,opt,name=spent,proto3" json:"spent,omitempty"`
	Released       int64                  `protobuf:"varint,5,opt,name=released,proto3" json:"released,omitempty"`
	Traffic        int64                  `protobuf:"varint,6,opt,name=traffic,proto3" json:"traffic,omitempty"`
	UnlimitedSpent int64                  `protobuf:"varint,7,opt,name=unlimited_spent,json=unlimitedSpent,proto3" json:"unlimited_spent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStateBaseline) Reset() {
	*x = UserStateBaseline{}
	mi := &file_api_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStateBaseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStateBaseline) ProtoMessage() {}

func (x *UserStateBaseline) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStateBaseline.ProtoReflect.Descriptor instead.
func (*UserStateBaseline) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{8}
}

func (x *UserStateBaseline) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStateBaseline) GetQuotaEpoch() int64 {
	if x != nil {
		return x.QuotaEpoch
	}
	return 0
}

func (x *UserStateBaseline) GetIssued() int64 {
	if x != nil {
		return x.Issued
	}
	return 0
}

func (x *UserStateBaseline) GetSpent() int64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *UserStateBaseline) GetReleased() int64 {
	if x != nil {
		return x.Released
	}
	return 0
}

func (x *UserStateBaseline) GetTraffic() int64 {
	if x != nil {
		return x.Traffic
	}
	return 0
}

func (x *UserStateBaseline) GetUnlimitedSpent() int64 {
	if x != nil {
		return x.UnlimitedSpent
	}
	return 0
}

type StateRestore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Users         []*UserStateBaseline   `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Rules         []*RuleUsage           `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRestore) Reset() {
	*x = StateRestore{}
	mi := &file_api_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRestore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRestore) ProtoMessage() {}

func (x *StateRestore) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRestore.ProtoReflect.Descriptor instead.
func (*StateRestore) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{9}
}

func (x *StateRestore) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StateRestore) GetUsers() []*UserStateBaseline {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *StateRestore) GetRules() []*RuleUsage {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRequest) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_api_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStatus) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UpdateStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Enabled               bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ListenHost            string                 `protobuf:"bytes,2,opt,name=listen_host,json=listenHost,proto3" json:"listen_host,omitempty"`
	PortMin               int32                  `protobuf:"varint,3,opt,name=port_min,json=portMin,proto3" json:"port_min,omitempty"`
	PortMax               int32                  `protobuf:"varint,4,opt,name=port_max,json=portMax,proto3" json:"port_max,omitempty"`
	MaxConnections        int64                  `protobuf:"varint,5,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	DialTimeoutSeconds    int32                  `protobuf:"varint,6,opt,name=dial_timeout_seconds,json=dialTimeoutSeconds,proto3" json:"dial_timeout_seconds,omitempty"`
	IdleTimeoutSeconds    int32                  `protobuf:"varint,7,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	ProbeIntervalSeconds  int32                  `protobuf:"varint,8,opt,name=probe_interval_seconds,json=probeIntervalSeconds,proto3" json:"probe_interval_seconds,omitempty"`
	DiskPath              string                 `protobuf:"bytes,9,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	NetworkInterfaces     []string               `protobuf:"bytes,10,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	TunnelExitEnabled     bool                   `protobuf:"varint,11,opt,name=tunnel_exit_enabled,json=tunnelExitEnabled,proto3" json:"tunnel_exit_enabled,omitempty"`
	TunnelListenHost      string                 `protobuf:"bytes,12,opt,name=tunnel_listen_host,json=tunnelListenHost,proto3" json:"tunnel_listen_host,omitempty"`
	TunnelListenPort      int32                  `protobuf:"varint,13,opt,name=tunnel_listen_port,json=tunnelListenPort,proto3" json:"tunnel_listen_port,omitempty"`
	NodeId                int64                  `protobuf:"varint,14,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TunnelProtocol        string                 `protobuf:"bytes,15,opt,name=tunnel_protocol,json=tunnelProtocol,proto3" json:"tunnel_protocol,omitempty"`
	Tls                   *TLSServerConfig       `protobuf:"bytes,16,opt,name=tls,proto3" json:"tls,omitempty"`
	Ddns                  *DDNSConfig            `protobuf:"bytes,17,opt,name=ddns,proto3" json:"ddns,omitempty"`
	ProxyTrustedCidrs     []string               `protobuf:"bytes,18,rep,name=proxy_trusted_cidrs,json=proxyTrustedCidrs,proto3" json:"proxy_trusted_cidrs,omitempty"`
	TargetDenyCidrs       []string               `protobuf:"bytes,19,rep,name=target_deny_cidrs,json=targetDenyCidrs,proto3" json:"target_deny_cidrs,omitempty"`
	SecurityConfigured    bool                   `protobuf:"varint,20,opt,name=security_configured,json=securityConfigured,proto3" json:"security_configured,omitempty"`
	UdpIdleTimeoutSeconds int32                  `protobuf:"varint,21,opt,name=udp_idle_timeout_seconds,json=udpIdleTimeoutSeconds,proto3" json:"udp_idle_timeout_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_api_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{12}
}

func (x *NodeConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NodeConfig) GetListenHost() string {
	if x != nil {
		return x.ListenHost
	}
	return ""
}

func (x *NodeConfig) GetPortMin() int32 {
	if x != nil {
		return x.PortMin
	}
	return 0
}

func (x *NodeConfig) GetPortMax() int32 {
	if x != nil {
		return x.PortMax
	}
	return 0
}

func (x *NodeConfig) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *NodeConfig) GetDialTimeoutSeconds() int32 {
	if x != nil {
		return x.DialTimeoutSeconds
	}
	return 0
}

func (x *NodeConfig) GetIdleTimeoutSeconds() int32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *NodeConfig) GetProbeIntervalSeconds() int32 {
	if x != nil {
		return x.ProbeIntervalSeconds
	}
	return 0
}

func (x *NodeConfig) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

func (x *NodeConfig) GetNetworkInterfaces() []string {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *NodeConfig) GetTunnelExitEnabled() bool {
	if x != nil {
		return x.TunnelExitEnabled
	}
	return false
}

func (x *NodeConfig) GetTunnelListenHost() string {
	if x != nil {
		return x.TunnelListenHost
	}
	return ""
}

func (x *NodeConfig) GetTunnelListenPort() int32 {
	if x != nil {
		return x.TunnelListenPort
	}
	return 0
}

func (x *NodeConfig) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeConfig) GetTunnelProtocol() string {
	if x != nil {
		return x.TunnelProtocol
	}
	return ""
}

func (x *NodeConfig) GetTls() *TLSServerConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *NodeConfig) GetDdns() *DDNSConfig {
	if x != nil {
		return x.Ddns
	}
	return nil
}

func (x *NodeConfig) GetProxyTrustedCidrs() []string {
	if x != nil {
		return x.ProxyTrustedCidrs
	}
	return nil
}

func (x *NodeConfig) GetTargetDenyCidrs() []string {
	if x != nil {
		return x.TargetDenyCidrs
	}
	return nil
}

func (x *NodeConfig) GetSecurityConfigured() bool {
	if x != nil {
		return x.SecurityConfigured
	}
	return false
}

func (x *NodeConfig) GetUdpIdleTimeoutSeconds() int32 {
	if x != nil {
		return x.UdpIdleTimeoutSeconds
	}
	return 0
}

type DDNSConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Generation      int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	RecordName      string                 `protobuf:"bytes,4,opt,name=record_name,json=recordName,proto3" json:"record_name,omitempty"`
	ZoneId          string                 `protobuf:"bytes,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Token           string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Ipv4            bool                   `protobuf:"varint,7,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6            bool                   `protobuf:"varint,8,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,9,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Ttl             int32                  `protobuf:"varint,10,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Ipv4Url         string                 `protobuf:"bytes,11,opt,name=ipv4_url,json=ipv4Url,proto3" json:"ipv4_url,omitempty"`
	Ipv6Url         string                 `protobuf:"bytes,12,opt,name=ipv6_url,json=ipv6Url,proto3" json:"ipv6_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DDNSConfig) Reset() {
	*x = DDNSConfig{}
	mi := &file_api_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDNSConfig) ProtoMessage() {}

func (x *DDNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDNSConfig.ProtoReflect.Descriptor instead.
func (*DDNSConfig) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{13}
}

func (x *DDNSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DDNSConfig) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DDNSConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DDNSConfig) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *DDNSConfig) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *DDNSConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DDNSConfig) GetIpv4() bool {
	if x != nil {
		return x.Ipv4
	}
	return false
}

func (x *DDNSConfig) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *DDNSConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *DDNSConfig) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DDNSConfig) GetIpv4Url() string {
	if x != nil {
		return x.Ipv4Url
	}
	return ""
}

func (x *DDNSConfig) GetIpv6Url() string {
	if x != nil {
		return x.Ipv6Url
	}
	return ""
}

type DDNSStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ipv4          string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          string                 `protobuf:"bytes,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	CheckedUnix   int64                  `protobuf:"varint,5,opt,name=checked_unix,json=checkedUnix,proto3" json:"checked_unix,omitempty"`
	UpdatedUnix   int64                  `protobuf:"varint,6,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDNSStatus) Reset() {
	*x = DDNSStatus{}
	mi := &file_api_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDNSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDNSStatus) ProtoMessage() {}

func (x *DDNSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDNSStatus.ProtoReflect.Descriptor instead.
func (*DDNSStatus) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{14}
}

func (x *DDNSStatus) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DDNSStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DDNSStatus) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *DDNSStatus) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *DDNSStatus) GetCheckedUnix() int64 {
	if x != nil {
		return x.CheckedUnix
	}
	return 0
}

func (x *DDNSStatus) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

func (x *DDNSStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TLSClientConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerName           string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Fingerprint          string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	RootCa               string                 `protobuf:"bytes,3,opt,name=root_ca,json=rootCa,proto3" json:"root_ca,omitempty"`
	Path                 string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	PoolSize             int32                  `protobuf:"varint,5,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	StreamWindowMib      int32                  `protobuf:"varint,6,opt,name=stream_window_mib,json=streamWindowMib,proto3" json:"stream_window_mib,omitempty"`
	ConnectionWindowMib  int32                  `protobuf:"varint,7,opt,name=connection_window_mib,json=connectionWindowMib,proto3" json:"connection_window_mib,omitempty"`
	Host                 string                 `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	RequireResponseProof bool                   `protobuf:"varint,9,opt,name=require_response_proof,json=requireResponseProof,proto3" json:"require_response_proof,omitempty"`
	SequenceAuth         bool                   `protobuf:"varint,10,opt,name=sequence_auth,json=sequenceAuth,proto3" json:"sequence_auth,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TLSClientConfig) Reset() {
	*x = TLSClientConfig{}
	mi := &file_api_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSClientConfig) ProtoMessage() {}

func (x *TLSClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSClientConfig.ProtoReflect.Descriptor instead.
func (*TLSClientConfig) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{15}
}

func (x *TLSClientConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSClientConfig) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *TLSClientConfig) GetRootCa() string {
	if x != nil {
		return x.RootCa
	}
	return ""
}

func (x *TLSClientConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TLSClientConfig) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *TLSClientConfig) GetStreamWindowMib() int32 {
	if x != nil {
		return x.StreamWindowMib
	}
	return 0
}

func (x *TLSClientConfig) GetConnectionWindowMib() int32 {
	if x != nil {
		return x.ConnectionWindowMib
	}
	return 0
}

func (x *TLSClientConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TLSClientConfig) GetRequireResponseProof() bool {
	if x != nil {
		return x.RequireResponseProof
	}
	return false
}

func (x *TLSClientConfig) GetSequenceAuth() bool {
	if x != nil {
		return x.SequenceAuth
	}
	return false
}

type TLSServerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServerName          string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Certificate         string                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey          string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Path                string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	StreamWindowMib     int32                  `protobuf:"varint,5,opt,name=stream_window_mib,json=streamWindowMib,proto3" json:"stream_window_mib,omitempty"`
	ConnectionWindowMib int32                  `protobuf:"varint,6,opt,name=connection_window_mib,json=connectionWindowMib,proto3" json:"connection_window_mib,omitempty"`
	MaxStreams          int32                  `protobuf:"varint,7,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	ChallengePort       int32                  `protobuf:"varint,8,opt,name=challenge_port,json=challengePort,proto3" json:"challenge_port,omitempty"`
	Challenges          []*ACMEChallenge       `protobuf:"bytes,9,rep,name=challenges,proto3" json:"challenges,omitempty"`
	SiteTitle           string                 `protobuf:"bytes,10,opt,name=site_title,json=siteTitle,proto3" json:"site_title,omitempty"`
	Host                string                 `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	FallbackUrl         string                 `protobuf:"bytes,12,opt,name=fallback_url,json=fallbackUrl,proto3" json:"fallback_url,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TLSServerConfig) Reset() {
	*x = TLSServerConfig{}
	mi := &file_api_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSServerConfig) ProtoMessage() {}

func (x *TLSServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSServerConfig.ProtoReflect.Descriptor instead.
func (*TLSServerConfig) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{16}
}

func (x *TLSServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSServerConfig) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *TLSServerConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *TLSServerConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TLSServerConfig) GetStreamWindowMib() int32 {
	if x != nil {
		return x.StreamWindowMib
	}
	return 0
}

func (x *TLSServerConfig) GetConnectionWindowMib() int32 {
	if x != nil {
		return x.ConnectionWindowMib
	}
	return 0
}

func (x *TLSServerConfig) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *TLSServerConfig) GetChallengePort() int32 {
	if x != nil {
		return x.ChallengePort
	}
	return 0
}

func (x *TLSServerConfig) GetChallenges() []*ACMEChallenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

func (x *TLSServerConfig) GetSiteTitle() string {
	if x != nil {
		return x.SiteTitle
	}
	return ""
}

func (x *TLSServerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TLSServerConfig) GetFallbackUrl() string {
	if x != nil {
		return x.FallbackUrl
	}
	return ""
}

type ACMEChallenge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Token            string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	KeyAuthorization string                 `protobuf:"bytes,3,opt,name=key_authorization,json=keyAuthorization,proto3" json:"key_authorization,omitempty"`
	Revision         int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	ExpiresUnix      int64                  `protobuf:"varint,5,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ACMEChallenge) Reset() {
	*x = ACMEChallenge{}
	mi := &file_api_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACMEChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACMEChallenge) ProtoMessage() {}

func (x *ACMEChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACMEChallenge.ProtoReflect.Descriptor instead.
func (*ACMEChallenge) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{17}
}

func (x *ACMEChallenge) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ACMEChallenge) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ACMEChallenge) GetKeyAuthorization() string {
	if x != nil {
		return x.KeyAuthorization
	}
	return ""
}

func (x *ACMEChallenge) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ACMEChallenge) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

type Probe struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SampledAt        int64                  `protobuf:"varint,1,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryTotal      int64                  `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed       int64                  `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	DiskTotal        int64                  `protobuf:"varint,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed         int64                  `protobuf:"varint,6,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	RxMbps           float64                `protobuf:"fixed64,7,opt,name=rx_mbps,json=rxMbps,proto3" json:"rx_mbps,omitempty"`
	TxMbps           float64                `protobuf:"fixed64,8,opt,name=tx_mbps,json=txMbps,proto3" json:"tx_mbps,omitempty"`
	TcpConnections   int64                  `protobuf:"varint,9,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	UdpSockets       int64                  `protobuf:"varint,10,opt,name=udp_sockets,json=udpSockets,proto3" json:"udp_sockets,omitempty"`
	Load1            float64                `protobuf:"fixed64,11,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5            float64                `protobuf:"fixed64,12,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15           float64                `protobuf:"fixed64,13,opt,name=load15,proto3" json:"load15,omitempty"`
	CpuReady         bool                   `protobuf:"varint,14,opt,name=cpu_ready,json=cpuReady,proto3" json:"cpu_ready,omitempty"`
	MemoryReady      bool                   `protobuf:"varint,15,opt,name=memory_ready,json=memoryReady,proto3" json:"memory_ready,omitempty"`
	DiskReady        bool                   `protobuf:"varint,16,opt,name=disk_ready,json=diskReady,proto3" json:"disk_ready,omitempty"`
	NetworkReady     bool                   `protobuf:"varint,17,opt,name=network_ready,json=networkReady,proto3" json:"network_ready,omitempty"`
	ConnectionsReady bool                   `protobuf:"varint,18,opt,name=connections_ready,json=connectionsReady,proto3" json:"connections_ready,omitempty"`
	LoadReady        bool                   `protobuf:"varint,19,opt,name=load_ready,json=loadReady,proto3" json:"load_ready,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Probe) Reset() {
	*x = Probe{}
	mi := &file_api_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{18}
}

func (x *Probe) GetSampledAt() int64 {
	if x != nil {
		return x.SampledAt
	}
	return 0
}

func (x *Probe) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Probe) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *Probe) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *Probe) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *Probe) GetDiskUsed() int64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *Probe) GetRxMbps() float64 {
	if x != nil {
		return x.RxMbps
	}
	return 0
}

func (x *Probe) GetTxMbps() float64 {
	if x != nil {
		return x.TxMbps
	}
	return 0
}

func (x *Probe) GetTcpConnections() int64 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *Probe) GetUdpSockets() int64 {
	if x != nil {
		return x.UdpSockets
	}
	return 0
}

func (x *Probe) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Probe) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Probe) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Probe) GetCpuReady() bool {
	if x != nil {
		return x.CpuReady
	}
	return false
}

func (x *Probe) GetMemoryReady() bool {
	if x != nil {
		return x.MemoryReady
	}
	return false
}

func (x *Probe) GetDiskReady() bool {
	if x != nil {
		return x.DiskReady
	}
	return false
}

func (x *Probe) GetNetworkReady() bool {
	if x != nil {
		return x.NetworkReady
	}
	return false
}

func (x *Probe) GetConnectionsReady() bool {
	if x != nil {
		return x.ConnectionsReady
	}
	return false
}

func (x *Probe) GetLoadReady() bool {
	if x != nil {
		return x.LoadReady
	}
	return false
}

var File_api_control_proto protoreflect.FileDescriptor

const file_api_control_proto_rawDesc = "" +
	"\n" +
	"\x11api/control.proto\x12\vnekopass.v1\"\xdf\x01\n" +
	"\x05Usage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05spent\x18\x02 \x01(\x03R\x05spent\x12\x1a\n" +
	"\breleased\x18\x03 \x01(\x03R\breleased\x12\x18\n" +
	"\atraffic\x18\x04 \x01(\x03R\atraffic\x12'\n" +
	"\x0funlimited_spent\x18\x05 \x01(\x03R\x0eunlimitedSpent\x12'\n" +
	"\x0fquota_unlimited\x18\x06 \x01(\bR\x0equotaUnlimited\x12\x1f\n" +
	"\vquota_epoch\x18\a \x01(\x03R\n" +
	"quotaEpoch\">\n" +
	"\tRuleUsage\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x18\n" +
	"\atraffic\x18\x02 \x01(\x03R\atraffic\"\x84\x05\n" +
	"\fAgentMessage\x12(\n" +
	"\x05usage\x18\x01 \x03(\v2\x12.nekopass.v1.UsageR\x05usage\x125\n" +
	"\n" +
	"rule_usage\x18\x02 \x03(\v2\x16.nekopass.v1.RuleUsageR\truleUsage\x12#\n" +
	"\rrequest_users\x18\x03 \x03(\x03R\frequestUsers\x12)\n" +
	"\x10applied_revision\x18\x04 \x01(\x03R\x0fappliedRevision\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\x03R\x11activeConnections\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x05probe\x18\b \x01(\v2\x12.nekopass.v1.ProbeR\x05probe\x12)\n" +
	"\x10protocol_version\x18\t \x01(\x05R\x0fprotocolVersion\x12\x19\n" +
	"\bacme_ack\x18\n" +
	" \x01(\x03R\aacmeAck\x128\n" +
	"\vddns_status\x18\v \x01(\v2\x17.nekopass.v1.DDNSStatusR\n" +
	"ddnsStatus\x12#\n" +
	"\ragent_version\x18\f \x01(\tR\fagentVersion\x12>\n" +
	"\rupdate_status\x18\r \x01(\v2\x19.nekopass.v1.UpdateStatusR\fupdateStatus\x12)\n" +
	"\x10update_supported\x18\x0e \x01(\bR\x0fupdateSupported\x12#\n" +
	"\rrestore_state\x18\x0f \x01(\bR\frestoreState\"\x9c\x02\n" +
	"\n" +
	"UserPolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12!\n" +
	"\fexpires_unix\x18\x03 \x01(\x03R\vexpiresUnix\x12\x1b\n" +
	"\tspeed_bps\x18\x04 \x01(\x03R\bspeedBps\x12\x16\n" +
	"\x06issued\x18\x05 \x01(\x03R\x06issued\x12'\n" +
	"\x0fmax_connections\x18\x06 \x01(\x03R\x0emaxConnections\x12\x19\n" +
	"\bip_limit\x18\a \x01(\x05R\aipLimit\x12'\n" +
	"\x0fquota_unlimited\x18\b \x01(\bR\x0equotaUnlimited\x12\x1f\n" +
	"\vquota_epoch\x18\t \x01(\x03R\n" +
	"quotaEpoch\"\x9f\x06\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vlisten_host\x18\x03 \x01(\tR\n" +
	"listenHost\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x12\x1f\n" +
	"\vtarget_host\x18\x05 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x06 \x01(\x05R\n" +
	"targetPort\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\x18\n" +
	"\atargets\x18\b \x03(\tR\atargets\x12\x18\n" +
	"\abalance\x18\t \x01(\tR\abalance\x12\x1b\n" +
	"\tspeed_bps\x18\n" +
	" \x01(\x03R\bspeedBps\x12\x19\n" +
	"\bip_limit\x18\v \x01(\x05R\aipLimit\x12)\n" +
	"\x10connection_limit\x18\f \x01(\x05R\x0fconnectionLimit\x12!\n" +
	"\fproxy_accept\x18\r \x01(\tR\vproxyAccept\x12\x1d\n" +
	"\n" +
	"proxy_send\x18\x0e \x01(\tR\tproxySend\x12.\n" +
	"\x13proxy_trusted_cidrs\x18\x0f \x03(\tR\x11proxyTrustedCidrs\x12$\n" +
	"\x0eegress_node_id\x18\x10 \x01(\x03R\fegressNodeId\x12\x1f\n" +
	"\vtunnel_host\x18\x11 \x01(\tR\n" +
	"tunnelHost\x12\x1f\n" +
	"\vtunnel_port\x18\x12 \x01(\x05R\n" +
	"tunnelPort\x12!\n" +
	"\ftunnel_token\x18\x13 \x01(\tR\vtunnelToken\x12&\n" +
	"\x0fingress_node_id\x18\x14 \x01(\x03R\ringressNodeId\x12'\n" +
	"\x0ftunnel_protocol\x18\x15 \x01(\tR\x0etunnelProtocol\x12.\n" +
	"\x03tls\x18\x16 \x01(\v2\x1c.nekopass.v1.TLSClientConfigR\x03tls\x12\x1f\n" +
	"\vquota_epoch\x18\x17 \x01(\x03R\n" +
	"quotaEpoch\x12\x1a\n" +
	"\bprotocol\x18\x18 \x01(\tR\bprotocol\"J\n" +
	"\n" +
	"TunnelLink\x12&\n" +
	"\x0fingress_node_id\x18\x01 \x01(\x03R\ringressNodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xe0\x01\n" +
	"\n" +
	"EgressRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12&\n" +
	"\x0fingress_node_id\x18\x02 \x01(\x03R\ringressNodeId\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vquota_epoch\x18\x05 \x01(\x03R\n" +
	"quotaEpoch\x12!\n" +
	"\fexpires_unix\x18\x06 \x01(\x03R\vexpiresUnix\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\"\x8b\x04\n" +
	"\x0eControlMessage\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12-\n" +
	"\x05users\x18\x02 \x03(\v2\x17.nekopass.v1.UserPolicyR\x05users\x12'\n" +
	"\x05rules\x18\x03 \x03(\v2\x11.nekopass.v1.RuleR\x05rules\x12+\n" +
	"\x04node\x18\x04 \x01(\v2\x17.nekopass.v1.NodeConfigR\x04node\x12A\n" +
	"\x12acknowledged_usage\x18\x05 \x03(\v2\x12.nekopass.v1.UsageR\x11acknowledgedUsage\x12:\n" +
	"\ftunnel_links\x18\x06 \x03(\v2\x17.nekopass.v1.TunnelLinkR\vtunnelLinks\x12:\n" +
	"\fegress_rules\x18\a \x03(\v2\x17.nekopass.v1.EgressRuleR\vegressRules\x122\n" +
	"\x06update\x18\b \x01(\v2\x1a.nekopass.v1.UpdateRequestR\x06update\x12)\n" +
	"\x10control_endpoint\x18\t \x01(\tR\x0fcontrolEndpoint\x12>\n" +
	"\rstate_restore\x18\n" +
	" \x01(\v2\x19.nekopass.v1.StateRestoreR\fstateRestore\"\xda\x01\n" +
	"\x11UserStateBaseline\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vquota_epoch\x18\x02 \x01(\x03R\n" +
	"quotaEpoch\x12\x16\n" +
	"\x06issued\x18\x03 \x01(\x03R\x06issued\x12\x14\n" +
	"\x05spent\x18\x04 \x01(\x03R\x05spent\x12\x1a\n" +
	"\breleased\x18\x05 \x01(\x03R\breleased\x12\x18\n" +
	"\atraffic\x18\x06 \x01(\x03R\atraffic\x12'\n" +
	"\x0funlimited_spent\x18\a \x01(\x03R\x0eunlimitedSpent\"\x93\x01\n" +
	"\fStateRestore\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x05users\x18\x02 \x03(\v2\x1e.nekopass.v1.UserStateBaselineR\x05users\x12,\n" +
	"\x05rules\x18\x03 \x03(\v2\x16.nekopass.v1.RuleUsageR\x05rules\"I\n" +
	"\rUpdateRequest\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"t\n" +
	"\fUpdateStatus\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xfd\x06\n" +
	"\n" +
	"NodeConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vlisten_host\x18\x02 \x01(\tR\n" +
	"listenHost\x12\x19\n" +
	"\bport_min\x18\x03 \x01(\x05R\aportMin\x12\x19\n" +
	"\bport_max\x18\x04 \x01(\x05R\aportMax\x12'\n" +
	"\x0fmax_connections\x18\x05 \x01(\x03R\x0emaxConnections\x120\n" +
	"\x14dial_timeout_seconds\x18\x06 \x01(\x05R\x12dialTimeoutSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\a \x01(\x05R\x12idleTimeoutSeconds\x124\n" +
	"\x16probe_interval_seconds\x18\b \x01(\x05R\x14probeIntervalSeconds\x12\x1b\n" +
	"\tdisk_path\x18\t \x01(\tR\bdiskPath\x12-\n" +
	"\x12network_interfaces\x18\n" +
	" \x03(\tR\x11networkInterfaces\x12.\n" +
	"\x13tunnel_exit_enabled\x18\v \x01(\bR\x11tunnelExitEnabled\x12,\n" +
	"\x12tunnel_listen_host\x18\f \x01(\tR\x10tunnelListenHost\x12,\n" +
	"\x12tunnel_listen_port\x18\r \x01(\x05R\x10tunnelListenPort\x12\x17\n" +
	"\anode_id\x18\x0e \x01(\x03R\x06nodeId\x12'\n" +
	"\x0ftunnel_protocol\x18\x0f \x01(\tR\x0etunnelProtocol\x12.\n" +
	"\x03tls\x18\x10 \x01(\v2\x1c.nekopass.v1.TLSServerConfigR\x03tls\x12+\n" +
	"\x04ddns\x18\x11 \x01(\v2\x17.nekopass.v1.DDNSConfigR\x04ddns\x12.\n" +
	"\x13proxy_trusted_cidrs\x18\x12 \x03(\tR\x11proxyTrustedCidrs\x12*\n" +
	"\x11target_deny_cidrs\x18\x13 \x03(\tR\x0ftargetDenyCidrs\x12/\n" +
	"\x13security_configured\x18\x14 \x01(\bR\x12securityConfigured\x127\n" +
	"\x18udp_idle_timeout_seconds\x18\x15 \x01(\x05R\x15udpIdleTimeoutSeconds\"\xcd\x02\n" +
	"\n" +
	"DDNSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1f\n" +
	"\vrecord_name\x18\x04 \x01(\tR\n" +
	"recordName\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\tR\x06zoneId\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12\x12\n" +
	"\x04ipv4\x18\a \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\b \x01(\bR\x04ipv6\x12)\n" +
	"\x10interval_seconds\x18\t \x01(\x05R\x0fintervalSeconds\x12\x10\n" +
	"\x03ttl\x18\n" +
	" \x01(\x05R\x03ttl\x12\x19\n" +
	"\bipv4_url\x18\v \x01(\tR\aipv4Url\x12\x19\n" +
	"\bipv6_url\x18\f \x01(\tR\aipv6Url\"\xc6\x01\n" +
	"\n" +
	"DDNSStatus\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x04 \x01(\tR\x04ipv6\x12!\n" +
	"\fchecked_unix\x18\x05 \x01(\x03R\vcheckedUnix\x12!\n" +
	"\fupdated_unix\x18\x06 \x01(\x03R\vupdatedUnix\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xed\x02\n" +
	"\x0fTLSClientConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x17\n" +
	"\aroot_ca\x18\x03 \x01(\tR\x06rootCa\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\tpool_size\x18\x05 \x01(\x05R\bpoolSize\x12*\n" +
	"\x11stream_window_mib\x18\x06 \x01(\x05R\x0fstreamWindowMib\x122\n" +
	"\x15connection_window_mib\x18\a \x01(\x05R\x13connectionWindowMib\x12\x12\n" +
	"\x04host\x18\b \x01(\tR\x04host\x124\n" +
	"\x16require_response_proof\x18\t \x01(\bR\x14requireResponseProof\x12#\n" +
	"\rsequence_auth\x18\n" +
	" \x01(\bR\fsequenceAuth\"\xc3\x03\n" +
	"\x0fTLSServerConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vcertificate\x18\x02 \x01(\tR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12*\n" +
	"\x11stream_window_mib\x18\x05 \x01(\x05R\x0fstreamWindowMib\x122\n" +
	"\x15connection_window_mib\x18\x06 \x01(\x05R\x13connectionWindowMib\x12\x1f\n" +
	"\vmax_streams\x18\a \x01(\x05R\n" +
	"maxStreams\x12%\n" +
	"\x0echallenge_port\x18\b \x01(\x05R\rchallengePort\x12:\n" +
	"\n" +
	"challenges\x18\t \x03(\v2\x1a.nekopass.v1.ACMEChallengeR\n" +
	"challenges\x12\x1d\n" +
	"\n" +
	"site_title\x18\n" +
	" \x01(\tR\tsiteTitle\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12!\n" +
	"\ffallback_url\x18\f \x01(\tR\vfallbackUrl\"\xa9\x01\n" +
	"\rACMEChallenge\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12+\n" +
	"\x11key_authorization\x18\x03 \x01(\tR\x10keyAuthorization\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12!\n" +
	"\fexpires_unix\x18\x05 \x01(\x03R\vexpiresUnix\"\xd7\x04\n" +
	"\x05Probe\x12\x1d\n" +
	"\n" +
	"sampled_at\x18\x01 \x01(\x03R\tsampledAt\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x03R\n" +
	"memoryUsed\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x03R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\x06 \x01(\x03R\bdiskUsed\x12\x17\n" +
	"\arx_mbps\x18\a \x01(\x01R\x06rxMbps\x12\x17\n" +
	"\atx_mbps\x18\b \x01(\x01R\x06txMbps\x12'\n" +
	"\x0ftcp_connections\x18\t \x01(\x03R\x0etcpConnections\x12\x1f\n" +
	"\vudp_sockets\x18\n" +
	" \x01(\x03R\n" +
	"udpSockets\x12\x14\n" +
	"\x05load1\x18\v \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\f \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\r \x01(\x01R\x06load15\x12\x1b\n" +
	"\tcpu_ready\x18\x0e \x01(\bR\bcpuReady\x12!\n" +
	"\fmemory_ready\x18\x0f \x01(\bR\vmemoryReady\x12\x1d\n" +
	"\n" +
	"disk_ready\x18\x10 \x01(\bR\tdiskReady\x12#\n" +
	"\rnetwork_ready\x18\x11 \x01(\bR\fnetworkReady\x12+\n" +
	"\x11connections_ready\x18\x12 \x01(\bR\x10connectionsReady\x12\x1d\n" +
	"\n" +
	"load_ready\x18\x13 \x01(\bR\tloadReady2P\n" +
	"\aControl\x12E\n" +
	"\aConnect\x12\x19.nekopass.v1.AgentMessage\x1a\x1b.nekopass.v1.ControlMessage(\x010\x01B0Z.github.com/nekopass/nekopass/internal/protocolb\x06proto3"

var (
	file_api_control_proto_rawDescOnce sync.Once
	file_api_control_proto_rawDescData []byte
)

func file_api_control_proto_rawDescGZIP() []byte {
	file_api_control_proto_rawDescOnce.Do(func() {
		file_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)))
	})
	return file_api_control_proto_rawDescData
}

var file_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_control_proto_goTypes = []any{
	(*Usage)(nil),             // 0: nekopass.v1.Usage
	(*RuleUsage)(nil),         // 1: nekopass.v1.RuleUsage
	(*AgentMessage)(nil),      // 2: nekopass.v1.AgentMessage
	(*UserPolicy)(nil),        // 3: nekopass.v1.UserPolicy
	(*Rule)(nil),              // 4: nekopass.v1.Rule
	(*TunnelLink)(nil),        // 5: nekopass.v1.TunnelLink
	(*EgressRule)(nil),        // 6: nekopass.v1.EgressRule
	(*ControlMessage)(nil),    // 7: nekopass.v1.ControlMessage
	(*UserStateBaseline)(nil), // 8: nekopass.v1.UserStateBaseline
	(*StateRestore)(nil),      // 9: nekopass.v1.StateRestore
	(*UpdateRequest)(nil),     // 10: nekopass.v1.UpdateRequest
	(*UpdateStatus)(nil),      // 11: nekopass.v1.UpdateStatus
	(*NodeConfig)(nil),        // 12: nekopass.v1.NodeConfig
	(*DDNSConfig)(nil),        // 13: nekopass.v1.DDNSConfig
	(*DDNSStatus)(nil),        // 14: nekopass.v1.DDNSStatus
	(*TLSClientConfig)(nil),   // 15: nekopass.v1.TLSClientConfig
	(*TLSServerConfig)(nil),   // 16: nekopass.v1.TLSServerConfig
	(*ACMEChallenge)(nil),     // 17: nekopass.v1.ACMEChallenge
	(*Probe)(nil),             // 18: nekopass.v1.Probe
}
var file_api_control_proto_depIdxs = []int32{
	0,  // 0: nekopass.v1.AgentMessage.usage:type_name -> nekopass.v1.Usage
	1,  // 1: nekopass.v1.AgentMessage.rule_usage:type_name -> nekopass.v1.RuleUsage
	18, // 2: nekopass.v1.AgentMessage.probe:type_name -> nekopass.v1.Probe
	14, // 3: nekopass.v1.AgentMessage.ddns_status:type_name -> nekopass.v1.DDNSStatus
	11, // 4: nekopass.v1.AgentMessage.update_status:type_name -> nekopass.v1.UpdateStatus
	15, // 5: nekopass.v1.Rule.tls:type_name -> nekopass.v1.TLSClientConfig
	3,  // 6: nekopass.v1.ControlMessage.users:type_name -> nekopass.v1.UserPolicy
	4,  // 7: nekopass.v1.ControlMessage.rules:type_name -> nekopass.v1.Rule
	12, // 8: nekopass.v1.ControlMessage.node:type_name -> nekopass.v1.NodeConfig
	0,  // 9: nekopass.v1.ControlMessage.acknowledged_usage:type_name -> nekopass.v1.Usage
	5,  // 10: nekopass.v1.ControlMessage.tunnel_links:type_name -> nekopass.v1.TunnelLink
	6,  // 11: nekopass.v1.ControlMessage.egress_rules:type_name -> nekopass.v1.EgressRule
	10, // 12: nekopass.v1.ControlMessage.update:type_name -> nekopass.v1.UpdateRequest
	9,  // 13: nekopass.v1.ControlMessage.state_restore:type_name -> nekopass.v1.StateRestore
	8,  // 14: nekopass.v1.StateRestore.users:type_name -> nekopass.v1.UserStateBaseline
	1,  // 15: nekopass.v1.StateRestore.rules:type_name -> nekopass.v1.RuleUsage
	16, // 16: nekopass.v1.NodeConfig.tls:type_name -> nekopass.v1.TLSServerConfig
	13, // 17: nekopass.v1.NodeConfig.ddns:type_name -> nekopass.v1.DDNSConfig
	17, // 18: nekopass.v1.TLSServerConfig.challenges:type_name -> nekopass.v1.ACMEChallenge
	2,  // 19: nekopass.v1.Control.Connect:input_type -> nekopass.v1.AgentMessage
	7,  // 20: nekopass.v1.Control.Connect:output_type -> nekopass.v1.ControlMessage
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_control_proto_init() }
func file_api_control_proto_init() {
	if File_api_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_proto_goTypes,
		DependencyIndexes: file_api_control_proto_depIdxs,
		MessageInfos:      file_api_control_proto_msgTypes,
	}.Build()
	File_api_control_proto = out.File
	file_api_control_proto_goTypes = nil
	file_api_control_proto_depIdxs = nil
}
