export type TunnelTLS = {server_name:string;client_sni:string;fingerprint:string;certificate_mode:string;certificate:string;private_key:string;root_ca:string;path:string;public_port:number;pool_size:number;stream_window_mib:number;connection_window_mib:number;max_streams:number;site_title:string;acme_email:string;acme_directory:string;acme_root_ca:string;http_challenge_port:number;dns_provider:string;dns_credentials:Record<string,string>}
export type Me = { id: number; username: string; is_admin: boolean }
export type User = { resources_revision: number; node_group_ids: number[]; id: number; username: string; is_admin: boolean; enabled: boolean; plan_id: number | null; plan_name: string; plan_enabled: boolean; plan_started_at: string; next_reset_at: string | null; quota_epoch: number; subscription_managed: boolean; balance_cents: number; expires_at: string | null; speed_mbps: number; quota_bytes: number; max_rules: number; max_connections: number; ip_limit: number; rule_speed_mbps: number; rule_ip_limit: number; rule_connection_limit: number; node_ids: number[]; rule_count: number; traffic_bytes: number; charged_bytes: number; allocated_bytes: number }
export type NodeInput = { tls: TunnelTLS; token: string; ingress_enabled: boolean; allow_direct: boolean; tunnel_exit_enabled: boolean; tunnel_protocol: string; tunnel_listen_host: string; tunnel_listen_port: number; tunnel_public_host: string; allowed_ingress_ids: number[]; name: string; public_address: string; notes: string; enabled: boolean; group_ids: number[]; listen_host: string; port_min: number; port_max: number; max_connections: number; dial_timeout_seconds: number; idle_timeout_seconds: number; probe_interval_seconds: number; disk_path: string; network_interfaces: string[] }
export type Node = NodeInput & {agent_version:string;update_supported:boolean;update_status:{generation:number;version:string;state:string;error:string}|null;tls_status:string;tls_error:string;tls_not_after:string|null;protocol_version:number; token: string; bound: boolean; id: number; online: boolean; last_seen: string | null; sync_error: string; active_connections: number; applied_revision: number; config_revision: number; rule_count: number }
export type RuleNode = Pick<Node, 'id' | 'name' | 'public_address' | 'online' | 'port_min' | 'port_max' | 'ingress_enabled' | 'allow_direct' | 'tunnel_exit_enabled' | 'allowed_ingress_ids' | 'tunnel_protocol'>
export type NodeGroup = { id: number; name: string; description: string; enabled: boolean; sort_order: number; strategy: string; node_ids: number[]; plan_count: number }
export type PlanInput = { purchase_limit: number; prices: Record<string,string|null>; name: string; description: string; enabled: boolean; speed_mbps: number; quota_bytes: number; max_rules: number; max_connections: number; ip_limit: number; rule_speed_mbps: number; rule_ip_limit: number; rule_connection_limit: number; duration_days: number; node_group_ids: number[] }
export type Plan = Omit<PlanInput,'prices'> & {prices: Record<string,number>} & { id: number; user_count: number }
export type Probe = { sampled_at?: number; cpu_percent?: number; memory_total?: number; memory_used?: number; disk_total?: number; disk_used?: number; rx_mbps?: number; tx_mbps?: number; tcp_connections?: number; udp_sockets?: number; load1?: number; load5?: number; load15?: number; cpu_ready?: boolean; memory_ready?: boolean; disk_ready?: boolean; network_ready?: boolean; connections_ready?: boolean; load_ready?: boolean }
export type ProbeNode = { id: number; name: string; group_id: number; group_name: string; enabled: boolean; online: boolean; metrics: Probe | null; updated_at: string | null }
export type RuleInput = { egress_node_id: number; user_id: number; node_id: number; name: string; group_id: number; listen_port: number; targets: string[]; balance: string; speed_mbps: number; ip_limit: number; connection_limit: number; proxy_accept: string; proxy_send: string; proxy_trusted_cidrs: string[]; enabled: boolean }
export type Rule = RuleInput & { egress_node_name: string; egress_tunnel_protocol?: string; id: number; username: string; node_name: string; public_address: string; traffic_bytes: number; status: string; sync_error: string; group_name: string; last_seen: string | null; applied_revision: number }
export type Group = { id: number; user_id: number; name: string; rule_count: number }
export async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> {
  const r = await fetch(`/api/v1/${path}`, { method, credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) })
  const data = await r.json()
  if (!r.ok) {
    if (r.status === 401 && location.pathname !== '/login') location.assign('/login?next=' + encodeURIComponent(location.pathname + location.search))
    throw new Error(data.error || `请求失败 (${r.status})`)
  }
  return data
}
export function bytes(n: number) { if (!n) return '0 B'; const i = Math.min(4, Math.floor(Math.log(n) / Math.log(1024))); return `${(n / 1024 ** i).toFixed(i ? 2 : 0)} ${['B', 'KiB', 'MiB', 'GiB', 'TiB'][i]}` }
export function address(host: string, port: number) { return `${host.includes(':') ? '[' + host + ']' : host}:${port}` }
export function quotaText(value: number) { return value === -1 ? '不限制' : bytes(value) }
export function limitText(value: number, unit = '') { return value === 0 ? '不限制' : `${value}${unit ? ' ' + unit : ''}` }
