<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, quotaText, limitText, type Plan, type PlanInput, type NodeGroup } from './api'
import Icon from './Icon.vue'
import LimitInput from './LimitInput.vue'
import {cycles,yuan,cycleName} from './commerce'
defineProps<{ plans: Plan[]; groups: NodeGroup[] }>()
const emit = defineEmits<{ refresh: [] }>()
const dialog = ref(false), editID = ref(0), busy = ref(false), quotaGiB = ref(100)
const defaults = (): PlanInput => ({ purchase_limit: 0, prices: {}, name: '', description: '', enabled: true, speed_mbps: 500, quota_bytes: 100 * 1024 ** 3, max_rules: 10, max_connections: 1000, ip_limit: 0, rule_speed_mbps: 0, rule_ip_limit: 0, rule_connection_limit: 0, duration_days: 30, node_group_ids: [] })
const form = reactive(defaults())
function edit(p?: Plan) { editID.value = p?.id || 0; const value = p || defaults(); Object.assign(form, defaults(), value, { prices: Object.fromEntries(cycles.map(c=>[c.key,p && p.prices[c.key]!==undefined?yuan(p.prices[c.key]):''])), node_group_ids: [...value.node_group_ids] }); quotaGiB.value = value.quota_bytes === -1 ? -1 : value.quota_bytes / 1024 ** 3; dialog.value = true }
async function save() { busy.value = true; try { await api(`admin/plans${editID.value ? '/' + editID.value : ''}`, editID.value ? 'PUT' : 'POST', { ...defaults(), ...Object.fromEntries(Object.keys(defaults()).map(k=>[k,(form as any)[k]])), quota_bytes: quotaGiB.value === -1 ? -1 : Math.round(quotaGiB.value * 1024 ** 3) }); dialog.value = false; emit('refresh'); ElMessage.success('套餐已保存，绑定用户将同步生效') } catch (e) { ElMessage.error((e as Error).message) } finally { busy.value = false } }
async function remove(p: Plan) { try { await ElMessageBox.confirm(`删除套餐「${p.name}」？已分配用户的套餐不能删除。`, '删除套餐', { confirmButtonText: '删除', cancelButtonText: '取消' }); await api(`admin/plans/${p.id}`, 'DELETE', {}); emit('refresh') } catch (e) { if (e instanceof Error) ElMessage.error(e.message) } }
</script>
<template>
 <section class="surface"><div class="section-header"><strong>套餐管理</strong><el-button type="primary" @click="edit()"><Icon name="add" />创建套餐</el-button></div><div class="section-body"><p class="subtle management-intro">用户的速度、流量、规则与节点组权限统一由套餐决定。修改套餐会同步影响绑定用户；周期套餐按月重置，购买或续费立即重置已用流量。</p><el-table :data="plans" empty-text="暂无套餐"><el-table-column prop="name" label="套餐名称" min-width="170" /><el-table-column label="售价" min-width="180"><template #default="{row}"><span v-if="!Object.keys(row.prices).length" class="subtle">未上架</span><div v-for="c in cycles.filter(c=>c.key in row.prices)" :key="c.key">{{c.label}} ¥{{yuan(row.prices[c.key])}}</div></template></el-table-column><el-table-column label="用户限速" width="130"><template #default="{ row }">{{ limitText(row.speed_mbps, 'Mbps') }}</template></el-table-column><el-table-column label="总流量" width="130"><template #default="{ row }">{{ quotaText(row.quota_bytes) }}</template></el-table-column><el-table-column label="手动分配期限" width="110"><template #default="{ row }">{{ row.duration_days ? row.duration_days + ' 天' : '永不到期' }}</template></el-table-column><el-table-column label="规则上限" width="100"><template #default="{ row }">{{ limitText(row.max_rules) }}</template></el-table-column><el-table-column label="节点组" min-width="200"><template #default="{ row }"><span v-if="!row.node_group_ids.length" class="subtle">无节点权限</span><el-tag v-for="id in row.node_group_ids" :key="id" class="group-chip">{{ groups.find(g => g.id === id)?.name || id }}</el-tag></template></el-table-column><el-table-column prop="user_count" label="用户数" width="90" /><el-table-column label="状态" width="90"><template #default="{ row }">{{ row.enabled ? '启用' : '停用' }}</template></el-table-column><el-table-column label="操作" width="135"><template #default="{ row }"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" :disabled="row.user_count > 0" @click="remove(row)">删除</el-button></template></el-table-column></el-table></div></section>
 <el-dialog v-model="dialog" :title="editID ? '编辑套餐' : '创建套餐'" width="680px" top="5vh" class="managed-form-dialog"><el-form :key="editID" label-position="top"><el-form-item label="套餐名称"><el-input v-model="form.name" maxlength="80" /></el-form-item><el-form-item label="套餐描述"><el-input v-model="form.description" type="textarea" :rows="2" /></el-form-item><div class="form-section-title">售价设置</div><p class="field-tip">金额留空时不出售该周期，填写 0 表示免费。周期套餐按月重置流量；一次性套餐永久有效，不自动重置。</p><div class="plan-prices-grid"><el-form-item v-for="cycle in cycles" :key="cycle.key" :label="cycle.label"><el-input v-model="form.prices[cycle.key]" inputmode="decimal" placeholder="不出售"><template #append>¥</template></el-input></el-form-item></div><p class="field-tip">资源限制留空即不限制，有效期留空即永不到期；流量填 0 表示零额度。其他套餐或节点限制仍然生效。</p><div class="form-section-title">用户资源限制</div><div class="form-grid"><el-form-item label="速度限制"><LimitInput v-model="form.speed_mbps" unit="Mbps" :min="1" :max="100000" /></el-form-item><el-form-item label="跨节点总流量额度"><LimitInput v-model="quotaGiB" unit="GiB" :sentinel="-1" :min="0" :max="1000000" :precision="3" /></el-form-item><el-form-item label="每用户购买上限（含续费）"><LimitInput v-model="form.purchase_limit" unit="次" :min="1" :max="1000000" /><span class="field-tip">累计成功购买次数，留空不限。免费套餐可设为 1 次；失败与重复请求不占次数。</span></el-form-item><el-form-item label="管理员手动分配有效期"><LimitInput v-model="form.duration_days" unit="天" :max="36500" unlimited-text="永不到期" /></el-form-item><el-form-item label="用户规则数量上限"><LimitInput v-model="form.max_rules" unit="条" :min="1" :max="10000" /></el-form-item><el-form-item label="每节点用户连接数上限"><LimitInput v-model="form.max_connections" unit="条" :min="1" :max="1000000" /></el-form-item><el-form-item label="每节点活跃 IP 上限"><LimitInput v-model="form.ip_limit" unit="个" :min="1" :max="1000000" /></el-form-item></div><div class="form-section-title">单规则限制</div><div class="form-grid"><el-form-item label="规则双向合计限速"><LimitInput v-model="form.rule_speed_mbps" unit="Mbps" :min="1" :max="100000" /></el-form-item><el-form-item label="规则活跃 IP 上限"><LimitInput v-model="form.rule_ip_limit" unit="个" :min="1" :max="1000000" /></el-form-item><el-form-item label="规则连接数上限"><LimitInput v-model="form.rule_connection_limit" unit="条" :min="1" :max="1000000" /></el-form-item></div><el-form-item label="允许使用的节点组"><el-select v-model="form.node_group_ids" multiple filterable placeholder="选择节点组"><el-option v-for="g in groups" :key="g.id" :label="g.name + (g.enabled ? '' : '（停用）')" :value="g.id" /></el-select><span class="field-tip">未选择节点组时，该套餐无法创建转发规则。</span></el-form-item><el-form-item label="启用套餐"><el-switch v-model="form.enabled" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存套餐</el-button></template></el-dialog>
</template>
