<script setup lang="ts">
import { computed } from 'vue'
import { bytes, type ProbeNode, type Probe } from './api'
import Icon from './Icon.vue'
const props = defineProps<{ nodes: ProbeNode[] }>()
const grouped = computed(() => { const map = new Map<number, { id: number; name: string; nodes: ProbeNode[] }>(); for (const n of props.nodes) { if (!map.has(n.group_id)) map.set(n.group_id, { id: n.group_id, name: n.group_name, nodes: [] }); map.get(n.group_id)!.nodes.push(n) }; return [...map.values()] })
function ready(n: ProbeNode, flag: keyof Probe) { return n.online && n.enabled && !!n.metrics?.[flag] }
function percent(used?: number, total?: number) { return total ? Math.max(0, Math.min(100, Number(used || 0) / Number(total) * 100)) : 0 }
function decimal(n?: number) { return Number(n || 0).toFixed(2) }
function color(value: number) { return value >= 90 ? '#f4919c' : value >= 75 ? '#e4b573' : '#6baaff' }
</script>
<template>
 <div class="probe-page"><div class="probe-page-heading"><div><h2>节点状态</h2><p class="subtle">查看可用节点的实时运行状态</p></div><span class="probe-live"><span></span>自动更新</span></div><el-empty v-if="!grouped.length" description="当前套餐暂无可查看的节点组" />
 <section v-for="g in grouped" :key="g.id" class="probe-group"><div class="probe-group-heading"><Icon name="folder" /><h3>{{ g.name }}</h3><span class="subtle">{{ g.nodes.filter(n => n.online && n.enabled).length }} / {{ g.nodes.length }} 在线</span></div><div class="probe-grid"><article v-for="n in g.nodes" :key="n.id" class="surface probe-card"><div class="probe-card-heading"><strong>{{ n.name }}</strong><span :class="['probe-status', { online: n.online && n.enabled }]">{{ !n.enabled ? '维护中' : n.online ? '在线' : '离线' }}</span></div>
 <div class="probe-bars"><div class="probe-meter"><div><span>CPU</span><strong>{{ ready(n, 'cpu_ready') ? decimal(n.metrics?.cpu_percent) + '%' : '—' }}</strong></div><el-progress :percentage="ready(n, 'cpu_ready') ? n.metrics?.cpu_percent || 0 : 0" :show-text="false" :stroke-width="7" :color="color(n.metrics?.cpu_percent || 0)" /></div><div class="probe-meter"><div><span>内存</span><strong>{{ ready(n, 'memory_ready') ? decimal(percent(n.metrics?.memory_used, n.metrics?.memory_total)) + '%' : '—' }}</strong></div><el-progress :percentage="ready(n, 'memory_ready') ? percent(n.metrics?.memory_used, n.metrics?.memory_total) : 0" :show-text="false" :stroke-width="7" :color="color(percent(n.metrics?.memory_used, n.metrics?.memory_total))" /><small>{{ ready(n, 'memory_ready') ? bytes(n.metrics?.memory_used || 0) + ' / ' + bytes(n.metrics?.memory_total || 0) : '等待采样' }}</small></div><div class="probe-meter"><div><span>硬盘</span><strong>{{ ready(n, 'disk_ready') ? decimal(percent(n.metrics?.disk_used, n.metrics?.disk_total)) + '%' : '—' }}</strong></div><el-progress :percentage="ready(n, 'disk_ready') ? percent(n.metrics?.disk_used, n.metrics?.disk_total) : 0" :show-text="false" :stroke-width="7" :color="color(percent(n.metrics?.disk_used, n.metrics?.disk_total))" /><small>{{ ready(n, 'disk_ready') ? bytes(n.metrics?.disk_used || 0) + ' / ' + bytes(n.metrics?.disk_total || 0) : '等待采样' }}</small></div></div>
 <div class="probe-network"><div><span>↓ 接收</span><strong>{{ ready(n, 'network_ready') ? decimal(n.metrics?.rx_mbps) : '—' }} <small>Mbps</small></strong></div><div><span>↑ 发送</span><strong>{{ ready(n, 'network_ready') ? decimal(n.metrics?.tx_mbps) : '—' }} <small>Mbps</small></strong></div></div><div class="probe-bottom"><div><span>网络连接数</span><strong>{{ ready(n, 'connections_ready') ? Number(n.metrics?.tcp_connections || 0) + Number(n.metrics?.udp_sockets || 0) : '—' }}</strong><small>{{ ready(n, 'connections_ready') ? `TCP ${n.metrics?.tcp_connections || 0} · UDP ${n.metrics?.udp_sockets || 0}` : '暂无数据' }}</small></div><div><span>服务器负载</span><strong>{{ ready(n, 'load_ready') ? decimal(n.metrics?.load1) : '—' }}</strong><small>{{ ready(n, 'load_ready') ? `${decimal(n.metrics?.load1)} / ${decimal(n.metrics?.load5)} / ${decimal(n.metrics?.load15)}` : '暂无数据' }}</small></div></div>
 </article></div></section></div>
</template>
